export default {
  "console.submit": "Submit",

  "help.title": "Available commands:",
  "help.command.help": "help - Show available commands",
  "help.command.clear": "clear - Clear the console, note: cannot be undone",
  "help.command.settings": "settings - Open settings",
  "help.command.save": "save <slot number> - Save the game",
  "help.command.load": "load <slot number> - Load the game",
  "help.command.delete": "delete <slot number> - Delete the save in the slot",

  "message.system.inited":
    'Game initialized. Type "help" for a list of commands.',
  "message.system.invalidCommand":
    'Invalid command. Type "help" for a list of commands.',
  "message.system.gameNotLaunched":
    "Game is not launched, start a new game or load a saved game.",
  "message.system.notImplemented": "Not implemented yet.",
  "message.system.clickToContinue": "Click to continue...",
  "message.system.invalidSlot":
    "Invalid slot number, available slot numbers are 1 to 4.",
  "message.system.noSaveFound": "No save found in slot, starting a new game.",
  "message.system.deletedSave": "Deleted save in slot ",
  "message.system.saved": "Saved game in slot ",
  "message.system.loaded": "Loaded game from slot.",
  "message.system.slotAlreadyLoaded":
    "This slot is already loaded, please refresh page and load or load another slot.",
  "message.system.eventRunning": "Can't load game because an event is running.",
  "message.system.alphaVersion":
    "This is an alpha version mainly for development and testing, the current content is very limited, more contents and features will be added in the future.",
  "message.system.guiNotAvailable":
    "GUI is not implemented yet, use commands instead.",
  "message.game.notEnoughIngredient": "Not enough ingredient.",
  "message.game.notEnoughMoney": "Not enough money.",
  "message.game.notEnoughItem": "Not enough item.",
  "message.game.sold_": "Sold ",
  "message.game.earned_": "Earned ",

  "message.character.welcome": "Welcome to Reminiscence!",

  "ui.titleScreen": "Title Screen",
  "ui.newGame": "New Game",
  "ui.loadGame": "Load Game",
  "ui.settings": "Settings",
  "ui.gameScreen": "Game Screen",
  "ui.day": "Day",
  "ui.time": "Time",
  "ui.time.0": "Morning",
  "ui.time.1": "Afternoon",
  "ui.time.2": "Night",
  "ui.money": "Money",
  "ui.nextDay": "Next Day",
  "ui.nextTime": "Rest",
  "ui.inventory": "Inventory",
  "ui.recipes": "Recipes",
  "ui.shelf": "Shelf",
  "ui.purchase": "Purchase",
  "ui.emptyInventory": "Inventory is empty.",
  "ui.emptyShelf": "Shelf is empty.",
  "ui.makeCount": "Make Count",
  "ui.ingredients": "Ingredients",
  "ui.recipe": "Recipe",
  "ui.products": "Products",
  "ui.fame": "Fame",
  "ui.purchaseCount": "Purchase Count",
  "ui.price": "Price",

  "character.tip.name": "Tip",
  "character.ramii.name": "Ramii",
  "character.ella.name": "Ella",

  "reward.recipe": "<New recipe unlocked!>",
  "reward.item": "<Acquired some item!>",
  "reward.money": "<Received some money!>",
  "reward.fame": "<The bakery is more famous!>",

  "item.flour": "Flour",
  "item.flour.desc": "Made from wheat, basic bakery ingredient.",
  "item.sugar": "Sugar",
  "item.sugar.desc": "Sweet.",
  "item.butter": "Butter",
  "item.butter.desc": "The oil from milk.",
  "item.egg": "Egg",
  "item.egg.desc": "A common egg.",
  "item.salt": "Salt",
  "item.salt.desc": "Salty salt.",
  "item.soda": "Soda Powder",
  "item.soda.desc": "An alkaline powdery substance.",
  "item.cacao": "cacao Powder",
  "item.cacao.desc": "Powdered cacao beans.",
  "item.cinnamon": "Cinnamon Powder",
  "item.cinnamon.desc":
    "A slightly spicy powder made from the bark of cinnamon trees.",
  "item.vanilla": "Vanilla",
  "item.vanilla.desc":
    "The seeds of a kind of orchid, have a peculiar aromatic smell.",
  "item.milk": "Milk",
  "item.milk.desc": "Nutricious and delicious.",
  "item.cream": "Cream",
  "item.cream.desc": "A white liquid seperated from milk, full of fat.",
  "item.sesame": "Sesame",
  "item.sesame.desc": "Tiny seeds rich in oil.",
  "item.almond": "Almond",
  "item.almond.desc": "A common nut.",
  "item.peanut": "Peanut",
  "item.peanut.desc": "A nut grown in the soil.",

  "item.whiteBread": "White Bread",
  "item.whiteBread.desc": "A loaf of white bread.",
  "item.bagel": "Bagel",
  "item.bagel.desc": "A small round bread with a hole in the middle.",
  "item.pretzel": "Pretzel",
  "item.pretzel.desc":
    "A baked pastry made from dough that is shaped into a knot.",
  "item.toast": "Toast",
  "item.toast.desc": "Soft and sweet bread for your breakfast.",
  "item.cupcake": "Cupcake",
  "item.cupcake.desc": "A cake in a delicate paper cup, topped with frosting.",
};
