export default {
  "console.submit": "提交",

  "help.title": "可用命令:",
  "help.command.help": "help - 显示可用命令",
  "help.command.clear": "clear - 清空控制台，注意：不能撤销",
  "help.command.settings": "settings - 打开设置",
  "help.command.save": "save <槽位编号> - 保存游戏",
  "help.command.load": "load <槽位编号> - 载入游戏",
  "help.command.delete": "delete <槽位编号> - 删除指定槽位的存档",

  "message.system.inited": '游戏初始化完成。输入 "help" 以查看可用命令。',
  "message.system.invalidCommand": '无效命令。输入 "help" 以查看可用命令。',
  "message.system.gameNotLaunched": "游戏还没启动，请开始新游戏或载入存档。",
  "message.system.notImplemented": "尚未实现。",
  "message.system.clickToContinue": "点击继续...",
  "message.system.invalidSlot": "无效的槽位编号，可选的槽位编号为 1 至 4。",
  "message.system.noSaveFound": "槽位中没有存档，开始新游戏。",
  "message.system.deletedSave": "已删除槽位 ",
  "message.system.saved": "已保存游戏至槽位 ",
  "message.system.loaded": "已载入指定槽位的游戏。",
  "message.system.slotAlreadyLoaded":
    "该槽位已经载入，请刷新页面并重新载入或载入其他槽位。",
  "message.system.eventRunning": "无法载入游戏，因为有事件正在进行。",
  "message.system.alphaVersion":
    "这是一个测试版本，主要用于开发和测试，当前的内容还很少，后续将会加入更多内容和功能。",
  "message.system.guiNotAvailable": "GUI 尚未实现，请使用命令。",
  "message.game.notEnoughIngredient": "原料不够。",
  "message.game.notEnoughMoney": "没有足够的钱。",
  "message.game.notEnoughItem": "没有足够的物品。",
  "message.game.sold_": "卖出了",
  "message.game.earned_": "赚取了",
  "message,game": "",

  "message.character.welcome": "欢迎来到 Reminiscence！",

  "ui.titleScreen": "标题画面",
  "ui.newGame": "新游戏",
  "ui.loadGame": "载入游戏",
  "ui.settings": "设置",
  "ui.gameScreen": "游戏画面",
  "ui.day": "天数",
  "ui.time": "时间",
  "ui.time.0": "上午",
  "ui.time.1": "下午",
  "ui.time.2": "晚上",
  "ui.money": "金钱",
  "ui.nextDay": "下一天",
  "ui.nextTime": "休息",
  "ui.inventory": "库存",
  "ui.recipes": "配方",
  "ui.shelf": "货架",
  "ui.purchase": "采购",
  "ui.emptyInventory": "库存是空的。",
  "ui.emptyShelf": "货架是空的。",
  "ui.makeCount": "制作数量",
  "ui.ingredients": "原料",
  "ui.recipe": "配方",
  "ui.products": "产品",
  "ui.fame": "知名度",
  "ui.purchaseCount": "采购数量",
  "ui.price": "价格",

  "character.tip.name": "提示",
  "character.ramii.name": "Ramii",
  "character.ella.name": "Ella",

  "reward.recipe": "<解锁了新的配方!>",
  "reward.item": "<获得了一些物品!>",
  "reward.money": "<赚到了一些钱!>",
  "reward.fame": "<面包房变得更出名了。>",

  "item.flour": "面粉",
  "item.flour.desc": "用小麦磨成的基本烘焙原料。",
  "item.sugar": "糖",
  "item.sugar.desc": "很甜。",
  "item.butter": "黄油",
  "item.butter.desc": "来自牛奶的油脂。",
  "item.egg": "蛋",
  "item.egg.desc": "一个普通的蛋。",
  "item.salt": "盐",
  "item.salt.desc": "咸盐。",
  "item.soda": "苏打粉",
  "item.soda.desc": "一种碱性粉末状物质。",
  "item.cacao": "可可粉",
  "item.cacao.desc": "磨碎的可可豆。",
  "item.cinnamon": "肉桂粉",
  "item.cinnamon.desc": "肉桂树皮磨成的粉，味道略带辛辣。",
  "item.vanilla": "香草",
  "item.vanilla.desc": "一种兰花的种子，有一种独特的香味。",
  "item.milk": "牛奶",
  "item.milk.desc": "营养美味。",
  "item.cream": "奶油",
  "item.cream.desc": "从牛奶中分离的富含脂肪的白色液体。",
  "item.sesame": "芝麻",
  "item.sesame.desc": "富含油脂的微小种子。",
  "item.almond": "杏仁",
  "item.almond.desc": "一种常见的坚果。",
  "item.peanut": "花生",
  "item.peanut.desc": "长在地下的坚果。",

  "item.whiteBread": "白面包",
  "item.whiteBread.desc": "一块白面包。",
  "item.bagel": "贝果",
  "item.bagel.desc": "一个小圆面包，中间有个洞。",
  "item.pretzel": "椒盐卷饼",
  "item.pretzel.desc": "用扭结的面团烤制而成。",
  "item.toast": "吐司",
  "item.toast.desc": "柔软香甜的面包，适合你的早餐。",
  "item.cupcake": "纸杯蛋糕",
  "item.cupcake.desc": "装在精致纸杯中的蛋糕，上面装饰着糖霜。",
};
